CREATE TABLE [dbo].[Table]
(
	[FIRSTNAME] VARCHAR(10) NOT NULL PRIMARY KEY, 
    [LASTNAME] VARCHAR(10) NOT NULL, 
    [USERNAME] VARCHAR(10) NOT NULL, 
    [EMAIL_ID] VARCHAR(30) NOT NULL, 
    [PASSWORD] VARCHAR(10) NOT NULL, 
    [ADDRESS] VARCHAR(80) NOT NULL, 
    [CITY] VARCHAR(10) NOT NULL, 
    [COUNTRY] VARCHAR(10) NOT NULL, 
    [ACCOUNT_TYPE] VARCHAR(10) NOT NULL
)
